### ISSUE TITLE
Mind+ 1.7.1 does not work in Puavo

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#865]
Dear Puavo developers
I am an expert for playing with microcontroller boards. I just tested the Mind+ 1.7.1 from Puavo on my test device md-test006. I definitly does not work in Puavo! Mind+ 1.7.1 is rather old ... from 2021-07-30. DFRobot has no official updates for Linux in their Github. 

Mind+ is based on Scratch 3.0. I try to connect a Micro:bit v2 to Mind+ but I can't get it running. The software asks for an administrator password. Yes, I can enter my password on the Puavo device md-test006 because it's personal administered but this is not the normal case for students at school. But now I get a lot of system messages in the Mind+ connection popup.

```
未知问题：
/images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/CH341SER/ch34x.c:563:30: error: initialization of ‘void (*)(struct tty_struct *, struct usb_serial_port *, const struct ktermios *)’ from incompatible pointer type ‘void (*)(struct tty_struct *, struct usb_serial_port *, struct ktermios *)’ [-Werror=incompatible-pointer-types]
563 | .set_termios = ch341_set_termios,
| ^~~~~~~~~~~~~~~~~
/images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/CH341SER/ch34x.c:563:30: note: (near initialization for ‘ch341_device.set_termios’)
/images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/CH341SER/ch34x.c:570:30: error: initialization of ‘void (*)(struct usb_serial_port *)’ from incompatible pointer type ‘int (*)(struct usb_serial_port *)’ [-Werror=incompatible-pointer-types]
570 | .port_remove = ch341_port_remove,
| ^~~~~~~~~~~~~~~~~
/images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/CH341SER/ch34x.c:570:30: note: (near initialization for ‘ch341_device.port_remove’)
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-49-common/scripts/Makefile.build:255: /images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/CH341SER/ch34x.o] Fehler 1
make[1]: *** [/usr/src/linux-headers-6.1.0-49-common/Makefile:2050: /images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/CH341SER] Fehler 2
make: *** [Makefile:5: default] Fehler 2
/images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/Linux_3.x.x_4.x.x_VCP_Driver_Source/cp210x.c:273:35: error: initialization of ‘void (*)(struct tty_struct *, struct usb_serial_port *, const struct ktermios *)’ from incompatible pointer type ‘void (*)(struct tty_struct *, struct usb_serial_port *, struct ktermios *)’ [-Werror=incompatible-pointer-types]
273 | .set_termios = cp210x_set_termios,
| ^~~~~~~~~~~~~~~~~~
/images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/Linux_3.x.x_4.x.x_VCP_Driver_Source/cp210x.c:273:35: note: (near initialization for ‘cp210x_device.set_termios’)
/images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/Linux_3.x.x_4.x.x_VCP_Driver_Source/cp210x.c:283:35: error: initialization of ‘void (*)(struct usb_serial_port *)’ from incompatible pointer type ‘int (*)(struct usb_serial_port *)’ [-Werror=incompatible-pointer-types]
283 | .port_remove = cp210x_port_remove,
| ^~~~~~~~~~~~~~~~~~
/images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/Linux_3.x.x_4.x.x_VCP_Driver_Source/cp210x.c:283:35: note: (near initialization for ‘cp210x_device.port_remove’)
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-49-common/scripts/Makefile.build:255: /images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/Linux_3.x.x_4.x.x_VCP_Driver_Source/cp210x.o] Fehler 1
make[1]: *** [/usr/src/linux-headers-6.1.0-49-common/Makefile:2050: /images/puavo-pkg/root/packages/mindplus/f5246fcc86cd15650644bf501ec1ddb5/upstream/opt/Mind+/drivers/Linux_3.x.x_4.x.x_VCP_Driver_Source] Fehler 2
make: *** [Makefile:7: all] Fehler 2
```

As I know there is no need to install a serial driver for the Micro:bit. The Micro:bit properly communicates in a lot of IDEs without any problem (MakeCode, MicroBlocks, Arduino, MicroPython). 

Is there any of your schools using Mind+ 1.7.1 in Puavo? If yes then I would like to read how they get it working. If no then you should delete the Puavo pkg for Mind+ from your Github repository and also from the PuavoConf. I already wrote about Mind+ in https://github.com/puavo-org/puavo-os/issues/736 ... yes, this issue is still open and everything I wrote is is currently valid. If you want to hold Mind+ for Puavo in the next Puavo with Trixie then it also does not work. 

Best regards,
Ralf

**Comment by ralf-krause** [comment]
If any school wants to use something like Scratch for microcontrollers (Micro:bit, Calliope, XIAO ESP32C3, XIAO nRF52840) then you should tell them about MicroBlocks https://microblocks.fun ... the software supports a very lot of microcontroller boards used at school. Yes, it's open source and it works in the Chromium browser and also in Google Chrome. You can connect. program, and controll the Micro:bit v2 and the Calliope v3 via USB and over the air via BLE. It's a very nice software!

The MicroBlocks software does not need any Scratch Link software. Scratch Link does not work in Puavo Bookworm and Trixie.
